version: '3'
services:

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10.0.0.1:8000:80

  oro:
    build: ./oro
    volumes:
      - ./nginx_logfiles:/var/log/nginx
#    ports:
#      - 8000:80
#      - 8080:8080

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=oro
      - MYSQL_USER=oro
      - MYSQL_PASSWORD=oropw
    restart: always
    volumes:
#      - ./db_data:/var/lib/mysql
      - ./mysql/my.oro.cnf:/etc/mysql/my.cnf
      - ./mysql/db_dump/:/docker-entrypoint-initdb.d/
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
