version: '3'
services:

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - oro

  oro:
    build: 
      context: ./oro
      dockerfile: Dockerfile.install
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./oro/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - INSTALL_VERSION=4.1.3
      - DB_USER=root
      - DB_PASSWORD=rootpw
      - DB_NAME=oro
      - APP_HOST=example.org
      - ORGNAME="Oro Inc"
      - APP_USER=admin
      - APP_PASSWORD=qwertz
      - APP_USER_EMAIL=admin@local
      - USER_FIRST_NAME=Bob
      - USER_LAST_NAME=Dylan
      - APP_LOAD_DEMO_DATA=n
    command: ["sh", "/docker-entrypoint.sh", "install"]

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=oro
      - MYSQL_USER=oro
      - MYSQL_PASSWORD=oropw
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/my.oro.cnf:/etc/mysql/my.cnf
      - ./mysql/db_dump/:/docker-entrypoint-initdb.d/
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
